### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [ChloeZeiter/Brainfuck#1]
This BF program should print "Hello World!" and a newline.
You have a problem with your looping construct.

``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by ChloeZeiter** [comment]
I think I see where its going wrong. Trying out some fixes now.

**Comment by ChloeZeiter** [comment]
Completely forgot about this issue. After remaking the interpreter it works for the Hello World program you provided, aswell as everything else I threw at it. Should be fixed. In the near future I will likely add some optimizations to it, but for now it seems functional.
